### ISSUE TITLE
App crashes when sliding down

### ISSUE THREAD

**Issue by eebssk1** [Andrerm124/ARTDeoptimiser#1]
The App always crashes when sliding down.
It crashes when many AppNames begin with 'S' appear in list.
The following is uncaught exception detected by scoop

`java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setOnClickListener(android.view.View$OnClickListener)' on a null object reference
	at com.ljmu.andre.artdeoptimiser.PackageListAdapter.buildSnapToolsAdvertRow(PackageListAdapter.java:77)
	at com.ljmu.andre.artdeoptimiser.PackageListAdapter.getView(PackageListAdapter.java:55)
	at android.widget.AbsListView.obtainView(AbsListView.java:2405)
	at android.widget.ListView.makeAndAddView(ListView.java:2052)
	at android.widget.ListView.fillDown(ListView.java:786)
	at android.widget.ListView.fillGap(ListView.java:750)
	at android.widget.AbsListView.trackMotionScroll(AbsListView.java:5416)
	at android.widget.ListView.trackMotionScroll(ListView.java:1971)
	at android.widget.AbsListView$FlingRunnable.run(AbsListView.java:4960)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
	at android.view.Choreographer.doCallbacks(Choreographer.java:723)
	at android.view.Choreographer.doFrame(Choreographer.java:655)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6499)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:108)`

**Comment by eebssk1** [comment]
Closed due to inactivity (historitic issues cleanup).
